<?php
declare(strict_types=1);
admin_required();
$route=rtrim($path,'/');
if($route==='/admin/links/delete'&&$method==='POST'){csrf_check();db()->prepare("UPDATE payment_links SET status='CANCELED' WHERE id=?")->execute([(int)($_POST['id']??0)]);header('Location: /admin',true,303);exit;}
if($route==='/admin/links/copy'&&$method==='GET'){$id=(int)($_GET['id']??0);$raw=public_token();$q=db()->prepare('SELECT id FROM payment_links WHERE id=?');$q->execute([$id]);if(!$q->fetch()){http_response_code(404);exit('Link nao encontrado');}db()->prepare("UPDATE payment_links SET token_hash=?,status='ACTIVE' WHERE id=?")->execute([token_hash($raw),$id]);$_SESSION['copied_url']=rtrim((string)envv('APP_URL'),' /').'/pagar/'.$raw;header('Location: /admin',true,303);exit;}
$links=[];$total=0;$activeCount=0;$paid=0;$loadError=null;
if($route==='/admin'){try{$pdo=db();$links=$pdo->query('SELECT id,description,amount_cents,payment_type,status FROM payment_links ORDER BY id DESC LIMIT 50')->fetchAll();$total=(int)$pdo->query('SELECT COUNT(*) FROM payment_links')->fetchColumn();$activeCount=(int)$pdo->query("SELECT COUNT(*) FROM payment_links WHERE status='ACTIVE'")->fetchColumn();$paid=(int)$pdo->query("SELECT COUNT(*) FROM payment_intents WHERE status='PAID'")->fetchColumn();}catch(Throwable $e){$loadError='N&atilde;o foi poss&iacute;vel carregar os dados financeiros.';error_log('[admin] '.$e->getMessage());}}
$title=$route==='/admin'?'Vis&atilde;o geral':($route==='/admin/services'?'Servi&ccedil;os':($route==='/admin/customers'?'Clientes':'Nova cobran&ccedil;a'));
?><!doctype html><html lang="pt-BR"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=htmlspecialchars_decode($title)?> | Checkout 360BH</title><link rel="stylesheet" href="/assets/admin.css?v=20260925"><style>.row-actions{display:flex;gap:8px;align-items:center;white-space:nowrap}.row-actions a,.row-actions button{border:0;background:#edf4fb;color:#075b9c;border-radius:7px;padding:7px 9px;cursor:pointer;text-decoration:none}.row-actions .danger{background:#fff0ef;color:#b42318}.copy-box{display:flex;gap:8px;margin:12px 0}.copy-box input{flex:1;padding:11px;border:1px solid #bcccdc;border-radius:8px}</style></head><body><div class="admin-shell"><aside class="sidebar"><div class="brand">360BH<small>Checkout financeiro</small></div><nav class="nav"><a class="<?=$route==='/admin'?'active':''?>" href="/admin">&#9632; Vis&atilde;o geral</a><a class="<?=$route==='/admin/services'?'active':''?>" href="/admin/services">&#9881; Servi&ccedil;os</a><a class="<?=$route==='/admin/customers'?'active':''?>" href="/admin/customers">&#128100; Clientes</a><a href="/admin/links/new">&#43; Criar cobran&ccedil;a</a></nav><div class="sidebar-footer"><a href="/admin/logout">Sair da conta</a></div></aside><section class="main"><header class="topbar"><button class="menu-toggle" onclick="document.querySelector('.sidebar').classList.toggle('open')">&#9776;</button><h1><?=htmlspecialchars_decode($title)?></h1><a class="btn btn-light" href="/admin/links/new">Novo link</a></header><main class="content">
<?php if($route==='/admin'): ?>
<div class="welcome"><h2>Ol&aacute;, administrador</h2><p class="muted">Acompanhe seus links e cobran&ccedil;as em um s&oacute; lugar.</p></div>
<?php if($loadError):?><div class="error"><?=htmlspecialchars_decode($loadError)?></div><?php endif;?>
<?php if(!empty($_SESSION['copied_url'])):$copied=$_SESSION['copied_url'];unset($_SESSION['copied_url']);?><section class="panel"><strong>Link p&uacute;blico atualizado:</strong><div class="copy-box"><input id="copied-url" readonly value="<?=htmlspecialchars($copied)?>"><button class="btn" type="button" onclick="navigator.clipboard.writeText(document.getElementById('copied-url').value)">Copiar</button></div></section><?php endif;?>
<section class="cards"><div class="card"><div class="card-label">Links criados</div><div class="card-value"><?=$total?></div></div><div class="card"><div class="card-label">Links ativos</div><div class="card-value"><?=$activeCount?></div></div><div class="card"><div class="card-label">Pagamentos aprovados</div><div class="card-value"><?=$paid?></div></div><div class="card"><div class="card-label">Gateway</div><div class="card-value" style="font-size:20px">Asaas</div></div></section>
<section class="panel"><div class="panel-header"><h2>Links de cobran&ccedil;a recentes</h2><a class="btn" href="/admin/links/new">Criar link</a></div><div class="table-wrap"><table><thead><tr><th>ID</th><th>Descri&ccedil;&atilde;o</th><th>Valor</th><th>Tipo</th><th>Status</th><th>A&ccedil;&otilde;es</th></tr></thead><tbody><?php foreach($links as $l):?><tr><td>#<?=$l['id']?></td><td><?=htmlspecialchars($l['description'])?></td><td>R$ <?=money((int)$l['amount_cents'])?></td><td><?=htmlspecialchars($l['payment_type'])?></td><td><span class="status status-<?=strtolower($l['status'])?>"><?=htmlspecialchars($l['status'])?></span></td><td><div class="row-actions"><a href="/admin/links/copy?id=<?=$l['id']?>" title="Copiar link">Copiar</a><a href="/admin/links/new?edit=<?=$l['id']?>" title="Editar">Editar</a><?php if($l['status']==='ACTIVE'):?><form method="post" action="/admin/links/delete" onsubmit="return confirm('Cancelar este link?')"><input type="hidden" name="_csrf" value="<?=csrf_token()?>"><input type="hidden" name="id" value="<?=$l['id']?>"><button class="danger" title="Excluir">Excluir</button></form><?php endif;?></div></td></tr><?php endforeach;if(!$links):?><tr><td colspan="6" class="muted">Nenhum link criado ainda.</td></tr><?php endif;?></tbody></table></div></section>
<?php elseif($route==='/admin/services'||$route==='/admin/customers'):?><section class="panel"><h2><?=htmlspecialchars_decode($title)?></h2><p class="muted">Esta &aacute;rea est&aacute; dispon&iacute;vel para gerenciamento.</p></section>
<?php else: http_response_code(404);?><section class="panel"><h2>P&aacute;gina n&atilde;o encontrada</h2><a class="btn" href="/admin">Voltar</a></section><?php endif;?>
</main></section></div></body></html>
