<?php
if ($path === '/admin/login') {
    if ($method === 'POST') {
        $email=(string)($_POST['email']??''); $password=(string)($_POST['password']??'');
        if (hash_equals((string)envv('ADMIN_EMAIL',''),$email) && password_verify($password,(string)envv('ADMIN_PASSWORD_HASH',''))) { session_regenerate_id(true); $_SESSION['admin_authenticated']=true; header('Location: /admin'); exit; }
        $error='Credenciais inválidas';
    }
    ?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Entrar | Checkout 360BH</title><link rel="stylesheet" href="/assets/admin.css"></head><body class="login-page"><main class="login-card"><div class="brand">360BH <small>Checkout financeiro</small></div><h1>Acesso administrativo</h1><p class="muted">Gerencie cobranças e links de pagamento.</p><?php if(!empty($error)): ?><div class="error"><?=htmlspecialchars($error)?></div><?php endif; ?><form method="post"><div class="field"><label for="email">E-mail</label><input id="email" name="email" type="email" autocomplete="username" required></div><div class="field"><label for="password">Senha</label><input id="password" name="password" type="password" autocomplete="current-password" required></div><button class="btn" type="submit">Entrar no painel</button></form></main></body></html><?php exit;
}
if ($path === '/admin/logout') { session_destroy(); header('Location: /admin/login'); exit; }
admin_required();
if ($path === '/admin/links/new') {
    if ($method === 'POST') { csrf_check(); $raw=public_token(); db()->prepare('INSERT INTO payment_links(token_hash,amount_cents,currency,description,payment_type,expires_at,max_uses,created_by) VALUES(?,?,?,?,?,?,?,?)')->execute([token_hash($raw),(int)$_POST['amount_cents'],'BRL',$_POST['description'],$_POST['payment_type'],$_POST['expires_at']?:null,(int)$_POST['max_uses']?:1,envv('ADMIN_EMAIL')]); $url=rtrim((string)envv('APP_URL'),' /').'/pagar/'.$raw; }
    if (isset($url)) { ?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Link criado | Checkout 360BH</title><link rel="stylesheet" href="/assets/admin.css"></head><body><div class="admin-shell"><aside class="sidebar"><div class="brand">360BH <small>Checkout financeiro</small></div><nav class="nav"><a href="/admin">&#9632; Visão geral</a><a class="active" href="/admin/links/new">&#43; Criar cobrança</a></nav></aside><section class="main"><header class="topbar"><h1>Link criado</h1></header><main class="content"><div class="panel"><div class="notice">O link foi criado e já pode ser enviado ao cliente.</div><p><strong><?=htmlspecialchars($url)?></strong></p><div class="form-actions"><a class="btn" href="<?=htmlspecialchars($url)?>" target="_blank">Abrir checkout</a><a class="btn btn-light" href="/admin">Voltar ao painel</a></div></div></main></section></div></body></html><?php exit; }
    ?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Nova cobrança | Checkout 360BH</title><link rel="stylesheet" href="/assets/admin.css"></head><body><div class="admin-shell"><aside class="sidebar" id="sidebar"><div class="brand">360BH <small>Checkout financeiro</small></div><nav class="nav"><a href="/admin">&#9632; Visão geral</a><a class="active" href="/admin/links/new">&#43; Criar cobrança</a></nav><div class="sidebar-footer"><a href="/admin/logout">Sair da conta</a></div></aside><section class="main"><header class="topbar"><button class="menu-toggle" onclick="document.getElementById('sidebar').classList.toggle('open')" aria-label="Abrir menu">&#9776;</button><h1>Nova cobrança</h1></header><main class="content"><div class="welcome"><h2>Criar link de pagamento</h2><p class="muted">Envie uma cobrança segura sem expor dados do gateway.</p></div><section class="panel"><form method="post"><input type="hidden" name="_csrf" value="<?=csrf_token()?>"><div class="form-grid"><div class="field full"><label for="description">Descrição da cobrança</label><input id="description" name="description" placeholder="Ex.: Plano mensal Mapa Glico" required></div><div class="field"><label for="amount">Valor em centavos</label><input id="amount" name="amount_cents" type="number" min="1" step="1" placeholder="Ex.: 9900" required></div><div class="field"><label for="type">Tipo de cobrança</label><select id="type" name="payment_type"><option value="ONE_TIME">Pagamento avulso</option><option value="SUBSCRIPTION">Assinatura mensal</option></select></div><div class="field"><label for="expires">Expiração (opcional)</label><input id="expires" name="expires_at" type="datetime-local"></div><div class="field"><label for="uses">Limite de utilizações</label><input id="uses" name="max_uses" type="number" min="1" value="1"></div></div><div class="form-actions"><button class="btn" type="submit">Gerar link de pagamento</button><a class="btn btn-light" href="/admin">Cancelar</a></div></form></section></main></section></div></body></html><?php exit;
}
if ($path === '/admin') { $pdo=db(); $links=$pdo->query('SELECT id,description,amount_cents,payment_type,status,created_at FROM payment_links ORDER BY id DESC LIMIT 50')->fetchAll(); $totalLinks=(int)$pdo->query('SELECT COUNT(*) FROM payment_links')->fetchColumn(); $activeLinks=(int)$pdo->query("SELECT COUNT(*) FROM payment_links WHERE status='ACTIVE'")->fetchColumn(); $paid=(int)$pdo->query("SELECT COUNT(*) FROM payment_intents WHERE status='PAID'")->fetchColumn(); ?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Painel | Checkout 360BH</title><link rel="stylesheet" href="/assets/admin.css"></head><body><div class="admin-shell"><aside class="sidebar" id="sidebar"><div class="brand">360BH <small>Checkout financeiro</small></div><nav class="nav"><a class="active" href="/admin">&#9632; Visão geral</a><a href="/admin/links/new">&#43; Criar cobrança</a><a href="/admin">&#9776; Todas as cobranças</a></nav><div class="sidebar-footer"><a href="/admin/logout">Sair da conta</a></div></aside><section class="main"><header class="topbar"><button class="menu-toggle" onclick="document.getElementById('sidebar').classList.toggle('open')" aria-label="Abrir menu">&#9776;</button><h1>Visão geral</h1><a class="btn btn-light" href="/admin/links/new">Novo link</a></header><main class="content"><div class="welcome"><h2>Olá, administrador</h2><p class="muted">Acompanhe seus links e cobranças em um só lugar.</p></div><section class="cards"><div class="card"><div class="card-label">Links criados</div><div class="card-value"><?=$totalLinks?></div></div><div class="card"><div class="card-label">Links ativos</div><div class="card-value"><?=$activeLinks?></div></div><div class="card"><div class="card-label">Pagamentos aprovados</div><div class="card-value"><?=$paid?></div></div><div class="card"><div class="card-label">Gateway</div><div class="card-value" style="font-size:20px">Asaas</div></div></section><section class="panel"><div class="panel-header"><h2>Links de cobrança recentes</h2><a class="btn" href="/admin/links/new">Criar link</a></div><div class="table-wrap"><table><thead><tr><th>ID</th><th>Descrição</th><th>Valor</th><th>Tipo</th><th>Status</th><th>Criado em</th></tr></thead><tbody><?php if(!$links): ?><tr><td colspan="6" class="muted">Nenhum link criado ainda.</td></tr><?php else: foreach($links as $l): ?><tr><td>#<?=$l['id']?></td><td><?=htmlspecialchars($l['description'])?></td><td>R$ <?=money((int)$l['amount_cents'])?></td><td><?=($l['payment_type']==='SUBSCRIPTION'?'Assinatura':'Avulso')?></td><td><span class="status status-<?=strtolower($l['status'])?>"><?=$l['status']?></span></td><td><?=date('d/m/Y H:i',strtotime($l['created_at']))?></td></tr><?php endforeach; endif; ?></tbody></table></div></section></main></section></div></body></html><?php exit; }
