<?php
declare(strict_types=1);
admin_required();
$route = rtrim($path, '/');
function page_start(string $title, string $active): void { ?>
<!doctype html><html lang="pt-BR"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=htmlspecialchars($title)?> | Checkout 360BH</title><link rel="stylesheet" href="/assets/admin.css?v=20260923"></head><body><div class="admin-shell"><aside class="sidebar"><div class="brand">360BH<small>Checkout financeiro</small></div><nav class="nav"><a class="<?=$active==='dashboard'?'active':''?>" href="/admin">&#9632; Vis&atilde;o geral</a><a class="<?=$active==='services'?'active':''?>" href="/admin/services">&#9881; Servi&ccedil;os</a><a class="<?=$active==='customers'?'active':''?>" href="/admin/customers">&#128100; Clientes</a><a class="<?=$active==='links'?'active':''?>" href="/admin/links/new">&#43; Criar cobran&ccedil;a</a></nav><div class="sidebar-footer"><a href="/admin/logout">Sair da conta</a></div></aside><section class="main"><header class="topbar"><button class="menu-toggle" onclick="document.querySelector('.sidebar').classList.toggle('open')">&#9776;</button><h1><?=htmlspecialchars($title)?></h1><a class="btn btn-light" href="/admin/links/new">Novo link</a></header><main class="content">
<?php }
function page_end(): void { ?></main></section></div></body></html><?php }
if ($route === '/admin') {
    $links=[];$total=0;$active=0;$paid=0;
    try {$pdo=db();$links=$pdo->query('SELECT id,description,amount_cents,payment_type,status,created_at FROM payment_links ORDER BY id DESC LIMIT 50')->fetchAll();$total=(int)$pdo->query('SELECT COUNT(*) FROM payment_links')->fetchColumn();$active=(int)$pdo->query("SELECT COUNT(*) FROM payment_links WHERE status='ACTIVE'")->fetchColumn();$paid=(int)$pdo->query("SELECT COUNT(*) FROM payment_intents WHERE status='PAID'")->fetchColumn();} catch(Throwable $e) { error_log($e->getMessage()); }
    page_start('Vis&atilde;o geral','dashboard'); ?><div class="welcome"><h2>Ol&aacute;, administrador</h2><p class="muted">Acompanhe seus links e cobran&ccedil;as em um s&oacute; lugar.</p></div><section class="cards"><div class="card"><div class="card-label">Links criados</div><div class="card-value"><?=$total?></div></div><div class="card"><div class="card-label">Links ativos</div><div class="card-value"><?=$active?></div></div><div class="card"><div class="card-label">Pagamentos aprovados</div><div class="card-value"><?=$paid?></div></div><div class="card"><div class="card-label">Gateway</div><div class="card-value" style="font-size:20px">Asaas</div></div></section><section class="panel"><div class="panel-header"><h2>Links de cobran&ccedil;a recentes</h2><a class="btn" href="/admin/links/new">Criar link</a></div><div class="table-wrap"><table><thead><tr><th>ID</th><th>Descri&ccedil;&atilde;o</th><th>Valor</th><th>Tipo</th><th>Status</th></tr></thead><tbody><?php foreach($links as $l): ?><tr><td>#<?=$l['id']?></td><td><?=htmlspecialchars($l['description'])?></td><td>R$ <?=money((int)$l['amount_cents'])?></td><td><?=htmlspecialchars($l['payment_type'])?></td><td><span class="status status-<?=strtolower($l['status'])?>"><?=htmlspecialchars($l['status'])?></span></td></tr><?php endforeach; if(!$links): ?><tr><td colspan="5" class="muted">Nenhum link criado ainda.</td></tr><?php endif; ?></tbody></table></div></section><?php page_end(); exit;
}
if ($route === '/admin/links/new') { if($method==='POST'){csrf_check();$raw=public_token();db()->prepare('INSERT INTO payment_links(token_hash,amount_cents,currency,description,payment_type,expires_at,max_uses,created_by) VALUES(?,?,?,?,?,?,?,?)')->execute([token_hash($raw),(int)$_POST['amount_cents'],'BRL',trim($_POST['description']),$_POST['payment_type'],$_POST['expires_at']?:null,(int)$_POST['max_uses']?:1,envv('ADMIN_EMAIL')]);$url=rtrim((string)envv('APP_URL'),' /').'/pagar/'.$raw;page_start('Link criado','links');?><div class="panel"><div class="notice">Link criado com sucesso.</div><p><strong><?=htmlspecialchars($url)?></strong></p><div class="form-actions"><a class="btn" href="<?=htmlspecialchars($url)?>" target="_blank">Abrir checkout</a><a class="btn btn-light" href="/admin">Voltar</a></div></div><?php page_end();exit;}page_start('Nova cobran&ccedil;a','links');?><div class="welcome"><h2>Criar link de pagamento</h2><p class="muted">Envie uma cobran&ccedil;a segura ao cliente.</p></div><section class="panel"><form method="post"><input type="hidden" name="_csrf" value="<?=csrf_token()?>"><div class="form-grid"><div class="field full"><label>Descri&ccedil;&atilde;o *</label><input name="description" required></div><div class="field"><label>Valor em centavos *</label><input name="amount_cents" type="number" min="1" required></div><div class="field"><label>Tipo *</label><select name="payment_type"><option value="ONE_TIME">Pagamento avulso</option><option value="SUBSCRIPTION">Assinatura mensal</option></select></div><div class="field"><label>Expira&ccedil;&atilde;o</label><input name="expires_at" type="datetime-local"></div><div class="field"><label>Limite de utiliza&ccedil;&otilde;es</label><input name="max_uses" type="number" min="1" value="1"></div></div><div class="form-actions"><button class="btn">Gerar link de pagamento</button><a class="btn btn-light" href="/admin">Cancelar</a></div></form></section><?php page_end();exit; }
if ($route === '/admin/services' || $route === '/admin/customers') { page_start($route==='/admin/services'?'Servi&ccedil;os':'Clientes',$route==='/admin/services'?'services':'customers'); ?><section class="panel"><h2>M&oacute;dulo <?=($route==='/admin/services'?'de servi&ccedil;os':'de clientes')?> preparado</h2><p class="muted">Acesse o dashboard para continuar a opera&ccedil;&atilde;o.</p></section><?php page_end();exit; }
http_response_code(404);echo 'Not found';
