<?php
declare(strict_types=1);
admin_required();
$route=rtrim($path,'/');
if($route==='/admin/links/delete'&&$method==='POST'){csrf_check();db()->prepare("UPDATE payment_links SET status='CANCELED' WHERE id=?")->execute([(int)($_POST['id']??0)]);header('Location: /admin',true,303);exit;}
if($route==='/admin/services'&&$method==='POST'){csrf_check();$name=trim((string)($_POST['name']??''));$webhook=trim((string)($_POST['webhook_url']??''));if($name==='')exit('Informe o nome do servico.');if($webhook!==''&&!filter_var($webhook,FILTER_VALIDATE_URL))exit('Informe uma URL de webhook valida.');$raw=public_token();db()->prepare('INSERT INTO services(name,api_key_hash,webhook_url,active) VALUES(?,?,?,1)')->execute([$name,hash('sha256',$raw),$webhook?:null]);$_SESSION['new_service_key']=$raw;header('Location: /admin/services',true,303);exit;}
if($route==='/admin/services/toggle'&&$method==='POST'){csrf_check();db()->prepare('UPDATE services SET active=IF(active=1,0,1) WHERE id=?')->execute([(int)($_POST['id']??0)]);header('Location: /admin/services',true,303);exit;}
if($route==='/admin/customers'&&$method==='POST'){csrf_check();$id=(int)($_POST['id']??0);$name=trim((string)($_POST['name']??''));$email=trim((string)($_POST['email']??''));$phone=preg_replace('/\D+/','',(string)($_POST['phone']??''));if($id<1||$name===''||!filter_var($email,FILTER_VALIDATE_EMAIL))exit('Dados invalidos.');db()->prepare('UPDATE customers SET name=?,email=?,phone=? WHERE id=?')->execute([$name,$email,$phone,$id]);header('Location: /admin/customers',true,303);exit;}
if($route==='/admin/links/copy'&&$method==='GET'){$id=(int)($_GET['id']??0);$raw=public_token();$q=db()->prepare('SELECT id FROM payment_links WHERE id=?');$q->execute([$id]);if(!$q->fetch()){http_response_code(404);exit('Link nao encontrado');}db()->prepare("UPDATE payment_links SET token_hash=?,status='ACTIVE' WHERE id=?")->execute([token_hash($raw),$id]);$_SESSION['copied_url']=rtrim((string)envv('APP_URL'),' /').'/pagar/'.$raw;header('Location: /admin',true,303);exit;}
$editing=null;
if($route==='/admin/links/new'){
    $editId=(int)($_GET['edit']??$_POST['id']??0);
    if($editId){$q=db()->prepare('SELECT * FROM payment_links WHERE id=?');$q->execute([$editId]);$editing=$q->fetch();if(!$editing){http_response_code(404);exit('Cobranca nao encontrada');}}
    if($method==='POST'){csrf_check();$description=trim((string)($_POST['description']??''));$amount=(int)($_POST['amount_cents']??0);$type=(string)($_POST['payment_type']??'ONE_TIME');$expires=$_POST['expires_at']?:null;$max=max(1,(int)($_POST['max_uses']??1));if($description===''||$amount<1)exit('Preencha os campos obrigatorios.');if($editId){db()->prepare('UPDATE payment_links SET description=?,amount_cents=?,payment_type=?,expires_at=?,max_uses=? WHERE id=?')->execute([$description,$amount,$type,$expires,$max,$editId]);header('Location: /admin',true,303);exit;}$raw=public_token();db()->prepare('INSERT INTO payment_links(token_hash,amount_cents,currency,description,payment_type,expires_at,max_uses,created_by) VALUES(?,?,?,?,?,?,?,?)')->execute([token_hash($raw),$amount,'BRL',$description,$type,$expires,$max,envv('ADMIN_EMAIL')]);$_SESSION['copied_url']=rtrim((string)envv('APP_URL'),' /').'/pagar/'.$raw;header('Location: /admin',true,303);exit;}
}
$links=[];$total=0;$activeCount=0;$paid=0;$loadError=null;
if($route==='/admin'){try{$pdo=db();$links=$pdo->query('SELECT id,description,amount_cents,payment_type,status FROM payment_links ORDER BY id DESC LIMIT 50')->fetchAll();$total=(int)$pdo->query('SELECT COUNT(*) FROM payment_links')->fetchColumn();$activeCount=(int)$pdo->query("SELECT COUNT(*) FROM payment_links WHERE status='ACTIVE'")->fetchColumn();$paid=(int)$pdo->query("SELECT COUNT(*) FROM payment_intents WHERE status='PAID'")->fetchColumn();}catch(Throwable $e){$loadError='N&atilde;o foi poss&iacute;vel carregar os dados financeiros.';error_log('[admin] '.$e->getMessage());}}
$title=$route==='/admin'?'Vis&atilde;o geral':($route==='/admin/services'?'Servi&ccedil;os':($route==='/admin/customers'?'Clientes':'Nova cobran&ccedil;a'));
?><!doctype html><html lang="pt-BR"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=htmlspecialchars_decode($title)?> | Checkout 360BH</title><link rel="stylesheet" href="/assets/admin.css?v=20260925"><style>.row-actions{display:flex;gap:8px;align-items:center;white-space:nowrap}.row-actions a,.row-actions button{border:0;background:#edf4fb;color:#075b9c;border-radius:7px;padding:7px 9px;cursor:pointer;text-decoration:none}.row-actions .danger{background:#fff0ef;color:#b42318}.copy-box{display:flex;gap:8px;margin:12px 0}.copy-box input{flex:1;padding:11px;border:1px solid #bcccdc;border-radius:8px}</style></head><body><div class="admin-shell"><aside class="sidebar"><div class="brand">360BH<small>Checkout financeiro</small></div><nav class="nav"><a class="<?=$route==='/admin'?'active':''?>" href="/admin">&#9632; Vis&atilde;o geral</a><a class="<?=$route==='/admin/services'?'active':''?>" href="/admin/services">&#9881; Servi&ccedil;os</a><a class="<?=$route==='/admin/customers'?'active':''?>" href="/admin/customers">&#128100; Clientes</a><a href="/admin/links/new">&#43; Criar cobran&ccedil;a</a></nav><div class="sidebar-footer"><a href="/admin/logout">Sair da conta</a></div></aside><section class="main"><header class="topbar"><button class="menu-toggle" onclick="document.querySelector('.sidebar').classList.toggle('open')">&#9776;</button><h1><?=htmlspecialchars_decode($title)?></h1><a class="btn btn-light" href="/admin/links/new">Novo link</a></header><main class="content">
<?php if($route==='/admin'): ?>
<div class="welcome"><h2>Ol&aacute;, administrador</h2><p class="muted">Acompanhe seus links e cobran&ccedil;as em um s&oacute; lugar.</p></div>
<?php if($loadError):?><div class="error"><?=htmlspecialchars_decode($loadError)?></div><?php endif;?>
<?php if(!empty($_SESSION['copied_url'])):$copied=$_SESSION['copied_url'];unset($_SESSION['copied_url']);?><section class="panel"><strong>Link p&uacute;blico atualizado:</strong><div class="copy-box"><input id="copied-url" readonly value="<?=htmlspecialchars($copied)?>"><button class="btn" type="button" onclick="navigator.clipboard.writeText(document.getElementById('copied-url').value)">Copiar</button></div></section><?php endif;?>
<section class="cards"><div class="card"><div class="card-label">Links criados</div><div class="card-value"><?=$total?></div></div><div class="card"><div class="card-label">Links ativos</div><div class="card-value"><?=$activeCount?></div></div><div class="card"><div class="card-label">Pagamentos aprovados</div><div class="card-value"><?=$paid?></div></div><div class="card"><div class="card-label">Gateway</div><div class="card-value" style="font-size:20px">Asaas</div></div></section>
<section class="panel"><div class="panel-header"><h2>Links de cobran&ccedil;a recentes</h2><a class="btn" href="/admin/links/new">Criar link</a></div><div class="table-wrap"><table><thead><tr><th>ID</th><th>Descri&ccedil;&atilde;o</th><th>Valor</th><th>Tipo</th><th>Status</th><th>A&ccedil;&otilde;es</th></tr></thead><tbody><?php foreach($links as $l):?><tr><td>#<?=$l['id']?></td><td><?=htmlspecialchars($l['description'])?></td><td>R$ <?=money((int)$l['amount_cents'])?></td><td><?=htmlspecialchars($l['payment_type'])?></td><td><span class="status status-<?=strtolower($l['status'])?>"><?=htmlspecialchars($l['status'])?></span></td><td><div class="row-actions"><a href="/admin/links/copy?id=<?=$l['id']?>" title="Copiar link">Copiar</a><a href="/admin/links/new?edit=<?=$l['id']?>" title="Editar">Editar</a><?php if($l['status']==='ACTIVE'):?><form method="post" action="/admin/links/delete" onsubmit="return confirm('Cancelar este link?')"><input type="hidden" name="_csrf" value="<?=csrf_token()?>"><input type="hidden" name="id" value="<?=$l['id']?>"><button class="danger" title="Excluir">Excluir</button></form><?php endif;?></div></td></tr><?php endforeach;if(!$links):?><tr><td colspan="6" class="muted">Nenhum link criado ainda.</td></tr><?php endif;?></tbody></table></div></section>
<?php elseif($route==='/admin/links/new'):?><div class="welcome"><h2><?=$editing?'Editar cobran&ccedil;a':'Criar link de pagamento'?></h2><p class="muted">Defina os dados da cobran&ccedil;a e gere um link seguro.</p></div><section class="panel"><form method="post"><input type="hidden" name="_csrf" value="<?=csrf_token()?>"><?php if($editing):?><input type="hidden" name="id" value="<?=$editing['id']?>"><?php endif;?><div class="form-grid"><div class="field full"><label>Descri&ccedil;&atilde;o *</label><input name="description" required value="<?=htmlspecialchars($editing['description']??'')?>"></div><div class="field"><label>Valor em centavos *</label><input name="amount_cents" type="number" min="1" required value="<?=htmlspecialchars((string)($editing['amount_cents']??''))?>"></div><div class="field"><label>Tipo *</label><select name="payment_type"><option value="ONE_TIME" <?=($editing['payment_type']??'')==='ONE_TIME'?'selected':''?>>Pagamento avulso</option><option value="SUBSCRIPTION" <?=($editing['payment_type']??'')==='SUBSCRIPTION'?'selected':''?>>Assinatura mensal</option></select></div><div class="field"><label>Expira&ccedil;&atilde;o</label><input name="expires_at" type="datetime-local" value="<?=!empty($editing['expires_at'])?date('Y-m-d\TH:i',strtotime($editing['expires_at'])):''?>"></div><div class="field"><label>Limite de utiliza&ccedil;&otilde;es</label><input name="max_uses" type="number" min="1" value="<?=htmlspecialchars((string)($editing['max_uses']??1))?>"></div></div><div class="form-actions"><button class="btn"><?=$editing?'Salvar altera&ccedil;&otilde;es':'Gerar link de pagamento'?></button><a class="btn btn-light" href="/admin">Cancelar</a></div></form></section>
<?php elseif($route==='/admin/services'): $services=db()->query('SELECT id,name,webhook_url,active,created_at FROM services ORDER BY id DESC')->fetchAll();?><div class="welcome"><h2>Servi&ccedil;os integrados</h2><p class="muted">Cadastre os sistemas que poder&atilde;o solicitar cobran&ccedil;as pela API.</p></div><?php if(!empty($_SESSION['new_service_key'])):$key=$_SESSION['new_service_key'];unset($_SESSION['new_service_key']);?><section class="panel"><div class="notice">Servi&ccedil;o criado. Guarde esta chave; ela n&atilde;o ser&aacute; exibida novamente.</div><div class="copy-box"><input id="service-key" readonly value="<?=htmlspecialchars($key)?>"><button class="btn" type="button" onclick="navigator.clipboard.writeText(document.getElementById('service-key').value)">Copiar chave</button></div></section><?php endif;?><section class="panel"><h2>Novo servi&ccedil;o</h2><form method="post"><input type="hidden" name="_csrf" value="<?=csrf_token()?>"><div class="form-grid"><div class="field"><label>Nome do servi&ccedil;o *</label><input name="name" required></div><div class="field"><label>Webhook de notifica&ccedil;&atilde;o</label><input name="webhook_url" type="url" placeholder="https://exemplo.com/webhook"></div></div><button class="btn">Cadastrar servi&ccedil;o</button></form></section><section class="panel"><h2>Servi&ccedil;os cadastrados</h2><div class="table-wrap"><table><thead><tr><th>ID</th><th>Nome</th><th>Webhook</th><th>Status</th><th>A&ccedil;&atilde;o</th></tr></thead><tbody><?php foreach($services as $service):?><tr><td>#<?=$service['id']?></td><td><?=htmlspecialchars($service['name'])?></td><td><?=htmlspecialchars($service['webhook_url']??'N&atilde;o configurado')?></td><td><?=$service['active']?'Ativo':'Inativo'?></td><td><form method="post" action="/admin/services/toggle"><input type="hidden" name="_csrf" value="<?=csrf_token()?>"><input type="hidden" name="id" value="<?=$service['id']?>"><button class="btn btn-light"><?=$service['active']?'Desativar':'Ativar'?></button></form></td></tr><?php endforeach;if(!$services):?><tr><td colspan="5" class="muted">Nenhum servi&ccedil;o cadastrado.</td></tr><?php endif;?></tbody></table></div></section>
<?php elseif($route==='/admin/customers'): $customerEdit=null;if(!empty($_GET['edit'])){$cq=db()->prepare('SELECT * FROM customers WHERE id=?');$cq->execute([(int)$_GET['edit']]);$customerEdit=$cq->fetch();}$customers=db()->query('SELECT id,name,email,cpf_cnpj,phone,city,state,created_at FROM customers ORDER BY id DESC')->fetchAll();?><div class="welcome"><h2>Clientes</h2><p class="muted">Cadastros reutilizados nas cobran&ccedil;as e integra&ccedil;&otilde;es.</p></div><?php if($customerEdit):?><section class="panel"><h2>Editar cliente</h2><form method="post"><input type="hidden" name="_csrf" value="<?=csrf_token()?>"><input type="hidden" name="id" value="<?=$customerEdit['id']?>"><div class="form-grid"><div class="field"><label>Nome completo</label><input name="name" required value="<?=htmlspecialchars($customerEdit['name'])?>"></div><div class="field"><label>E-mail</label><input name="email" type="email" required value="<?=htmlspecialchars($customerEdit['email'])?>"></div><div class="field"><label>Celular</label><input name="phone" value="<?=htmlspecialchars($customerEdit['phone'])?>"></div></div><div class="form-actions"><button class="btn">Salvar altera&ccedil;&otilde;es</button><a class="btn btn-light" href="/admin/customers">Cancelar</a></div></form></section><?php endif;?><section class="panel"><div class="panel-header"><h2>Clientes cadastrados</h2><span class="muted"><?=count($customers)?> registro(s)</span></div><div class="table-wrap"><table><thead><tr><th>Cliente</th><th>CPF/CNPJ</th><th>Contato</th><th>Localidade</th><th>A&ccedil;&otilde;es</th></tr></thead><tbody><?php foreach($customers as $customer):?><tr><td><strong><?=htmlspecialchars($customer['name'])?></strong><br><small><?=htmlspecialchars($customer['email'])?></small></td><td><?=htmlspecialchars($customer['cpf_cnpj'])?></td><td><?=htmlspecialchars($customer['phone'])?></td><td><?=htmlspecialchars(trim(($customer['city']??'').' / '.($customer['state']??''),' /'))?></td><td><div class="row-actions"><a href="/admin/customers?edit=<?=$customer['id']?>">Editar</a><a href="/admin/links/new?customer=<?=$customer['id']?>">Cobrar</a></div></td></tr><?php endforeach;if(!$customers):?><tr><td colspan="5" class="muted">Nenhum cliente cadastrado ainda.</td></tr><?php endif;?></tbody></table></div></section>
<?php else: http_response_code(404);?><section class="panel"><h2>P&aacute;gina n&atilde;o encontrada</h2><a class="btn" href="/admin">Voltar</a></section><?php endif;?>
</main></section></div></body></html>
