<?php
declare(strict_types=1);
require dirname(__DIR__).'/bootstrap/app.php';
require dirname(__DIR__).'/app/Gateway.php';
session_start();
$path = parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH) ?: '/';
$method = $_SERVER['REQUEST_METHOD'];
if ($path === '/health') json_out(['ok'=>true,'app'=>'checkout-360bh']);
if ($path === '/api/public/customer-lookup' && $method === 'GET') { $cpf=preg_replace('/\D+/','',$_GET['cpf']??''); if($cpf==='') json_out(['found'=>false]); $q=db()->prepare('SELECT name,email,cpf_cnpj,phone,postal_code,address,address_number,complement,province,city,state FROM customers WHERE cpf_cnpj=? LIMIT 1'); $q->execute([$cpf]); $customer=$q->fetch(); json_out(['found'=>(bool)$customer,'customer'=>$customer?:null]); }
if (str_starts_with($path, '/pagar/')) { require __DIR__.'/checkout-ui-v2.php'; exit; }
if ($path === '/admin/login' || $path === '/admin/login/') { if ($method === 'POST' && hash_equals((string)envv('ADMIN_EMAIL',''),(string)($_POST['email']??'')) && password_verify((string)($_POST['password']??''),(string)envv('ADMIN_PASSWORD_HASH',''))) { session_regenerate_id(true); $_SESSION['admin_authenticated']=true; header('Location: /admin'); exit; } ?><!doctype html><html lang="pt-BR"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Entrar | Checkout 360BH</title><link rel="stylesheet" href="/assets/admin.css"></head><body class="login-page"><main class="login-card"><div class="brand">360BH <small>Checkout financeiro</small></div><h1>Acesso administrativo</h1><p class="muted">Gerencie cobran&ccedil;as e links de pagamento.</p><form method="post"><div class="field"><label>E-mail</label><input name="email" type="email" required></div><div class="field"><label>Senha</label><input name="password" type="password" required></div><button class="btn">Entrar no painel</button></form></main></body></html><?php exit; }
if ($path === '/admin/logout') { $_SESSION = []; if (ini_get('session.use_cookies')) { $p=session_get_cookie_params(); setcookie(session_name(), '', time()-42000, $p['path'], $p['domain'], (bool)$p['secure'], (bool)$p['httponly']); } session_destroy(); header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0'); header('Pragma: no-cache'); header('Location: /admin/login', true, 303); exit; }
if (str_starts_with($path, '/admin')) { header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0'); header('Pragma: no-cache'); require __DIR__.'/admin-ui-live-20260923.php'; exit; }
if ($path === '/api/v1/payments' && $method === 'POST') {
    $service=service_from_request(); $in=request_json(); foreach(['name','email','amount_cents','idempotency_key'] as $field) if(!isset($in[$field])||$in[$field]==='') json_out(['error'=>$field.' Ã© obrigatÃ³rio'],422);
    $pdo=db(); $q=$pdo->prepare('SELECT * FROM payment_intents WHERE idempotency_key=?'); $q->execute([$in['idempotency_key']]); if($old=$q->fetch()) json_out(['id'=>$old['public_id'],'status'=>$old['status'],'checkout_url'=>$old['checkout_url']]);
    $pdo->prepare('INSERT INTO customers(name,email,cpf_cnpj,phone) VALUES(?,?,?,?)')->execute([$in['name'],$in['email'],$in['cpf_cnpj']??null,$in['phone']??null]); $customerId=(int)$pdo->lastInsertId(); $gateway=new AsaasGateway(); $gatewayId=$gateway->createCustomer($in); $type=($in['type']??'ONE_TIME')==='SUBSCRIPTION'?'SUBSCRIPTION':'ONE_TIME'; $public=substr(bin2hex(random_bytes(16)),0,26);
    $pdo->prepare('INSERT INTO payment_intents(public_id,idempotency_key,service_id,customer_id,type,amount_cents,status) VALUES(?,?,?,?,?,?,?)')->execute([$public,$in['idempotency_key'],$service['id'],$customerId,$type,(int)$in['amount_cents'],'PROCESSING']); $intentId=(int)$pdo->lastInsertId();
    $args=['gateway_customer_id'=>$gatewayId,'amount_cents'=>(int)$in['amount_cents'],'description'=>$in['description']??'CobranÃ§a 360BH','external_reference'=>'intent:'.$intentId,'billing_type'=>$in['billing_type']??'UNDEFINED','due_date'=>$in['due_date']??date('Y-m-d'),'cycle'=>$in['cycle']??'MONTHLY']; $res=$type==='SUBSCRIPTION'?$gateway->createSubscription($args):$gateway->createPayment($args); $checkout=$res['invoiceUrl']??null; $pdo->prepare('UPDATE payment_intents SET gateway_id=?,checkout_url=?,status=? WHERE id=?')->execute([$res['id']??null,$checkout,'PENDING',$intentId]); json_out(['id'=>$public,'status'=>'PENDING','checkout_url'=>$checkout],201);
}
if ($path === '/api/v1/payment-intents' && $method === 'GET') { $service=service_from_request(); $id=$_GET['id']??''; $q=db()->prepare('SELECT public_id,status,amount_cents,checkout_url,created_at,updated_at FROM payment_intents WHERE public_id=? AND service_id=?'); $q->execute([$id,$service['id']]); if(!$row=$q->fetch()) json_out(['error'=>'not found'],404); json_out($row); }
if ($path === '/api/v1/payment-links' && $method === 'POST') {
    $service = service_from_request();
    $in = request_json();
    if (empty($in['amount_cents']) || empty($in['description'])) json_out(['error'=>'amount_cents e description sÃ£o obrigatÃ³rios'],422);
    $raw = public_token();
    db()->prepare('INSERT INTO payment_links(token_hash,amount_cents,currency,description,payment_type,expires_at,max_uses,created_by,service_id) VALUES(?,?,?,?,?,?,?,?,?)')->execute([token_hash($raw),(int)$in['amount_cents'],$in['currency']??'BRL',$in['description'],$in['payment_type']??'ONE_TIME',$in['expires_at']??null,$in['max_uses']??1,$service['name'],$service['id']]);
    json_out(['url'=>rtrim((string)envv('APP_URL'),' /').'/pagar/'.$raw],201);
}
if (preg_match('#^/pagar/([A-Za-z0-9_-]+)$#',$path,$matches)) {
    $stmt=db()->prepare('SELECT * FROM payment_links WHERE token_hash=?'); $stmt->execute([token_hash($matches[1])]); $link=$stmt->fetch();
    if (!$link || $link['status'] !== 'ACTIVE' || ($link['expires_at'] && strtotime($link['expires_at']) < time())) { http_response_code(404); exit('Link invÃ¡lido, expirado ou cancelado.'); }
    if ($method === 'POST') {
        $in=$_POST; if(empty($in['name'])||empty($in['email'])) exit('Nome e e-mail sÃ£o obrigatÃ³rios.');
        $pdo=db(); $pdo->prepare('INSERT INTO customers(name,email,cpf_cnpj,phone) VALUES(?,?,?,?)')->execute([$in['name'],$in['email'],$in['cpf_cnpj']??null,$in['phone']??null]); $gateway=new AsaasGateway(); $gatewayId=$gateway->createCustomer($in);
        $result=$link['payment_type']==='SUBSCRIPTION'?$gateway->createSubscription(['gateway_customer_id'=>$gatewayId,'amount_cents'=>$link['amount_cents'],'cycle'=>'MONTHLY','description'=>$link['description'],'external_reference'=>'link:'.$link['id']]):$gateway->createPayment(['gateway_customer_id'=>$gatewayId,'amount_cents'=>$link['amount_cents'],'description'=>$link['description'],'external_reference'=>'link:'.$link['id']]);
        $pdo->prepare("UPDATE payment_links SET uses_count=uses_count+1,status=IF(max_uses IS NOT NULL AND uses_count+1>=max_uses,'USED',status) WHERE id=?")->execute([$link['id']]); if(!empty($result['invoiceUrl'])) header('Location: '.$result['invoiceUrl'],true,303); exit('CobranÃ§a criada.');
    }
    ?><!doctype html><meta charset="utf-8"><title>Pagamento 360BH</title><h1><?=htmlspecialchars($link['description'])?></h1><p>Valor: R$ <?=money((int)$link['amount_cents'])?></p><form method="post"><input name="name" placeholder="Nome" required><input name="email" type="email" placeholder="E-mail" required><input name="cpf_cnpj" placeholder="CPF/CNPJ"><input name="phone" placeholder="Telefone"><button>Pagar</button></form><?php exit;
}
if ($path === '/webhook/asaas' && $method === 'POST') {
    $provided=$_SERVER['HTTP_ASAAS_ACCESS_TOKEN']??''; if(!hash_equals((string)envv('ASAAS_WEBHOOK_TOKEN',''),$provided)) json_out(['error'=>'unauthorized'],401); $payload=json_decode(file_get_contents('php://input'),true) ?: []; $event=$payload['id']??hash('sha256',json_encode($payload));
    $pdo=db(); try { $pdo->prepare('INSERT INTO webhook_events(gateway,event_id,event_name,payload,processed_at) VALUES(?,?,?,?,NOW())')->execute(['asaas',$event,$payload['event']??'unknown',json_encode($payload)]); } catch(PDOException $e) { if(($e->errorInfo[1]??0)!==1062) throw $e; else json_out(['received'=>true,'duplicate'=>true]); }
    $object=$payload['payment']??$payload['subscription']??[]; $gatewayId=$object['id']??null; $eventName=$payload['event']??''; $map=['PAYMENT_CONFIRMED'=>'PAID','PAYMENT_RECEIVED'=>'PAID','PAYMENT_OVERDUE'=>'OVERDUE','PAYMENT_DELETED'=>'CANCELED','PAYMENT_REFUNDED'=>'REFUNDED','SUBSCRIPTION_INACTIVATED'=>'CANCELED']; $newStatus=$map[$eventName]??null;
    if($gatewayId && $newStatus) { $q=$pdo->prepare('SELECT pi.*,s.webhook_url,s.webhook_secret_hash,s.id AS sid FROM payment_intents pi JOIN services s ON s.id=pi.service_id WHERE pi.gateway_id=?'); $q->execute([$gatewayId]); if($intent=$q->fetch()) { $pdo->prepare('UPDATE payment_intents SET status=? WHERE id=?')->execute([$newStatus,$intent['id']]); $serviceRow=$intent; notify_service($serviceRow,$eventName,['payment_id'=>$intent['public_id'],'status'=>$newStatus,'gateway_id'=>$gatewayId],(int)$intent['id']); } }
    json_out(['received'=>true]);
}
if ($path === '/admin/login') { if($method==='POST'){ $in=$_POST; if(hash_equals((string)envv('ADMIN_EMAIL',''),(string)($in['email']??'')) && password_verify((string)($in['password']??''),(string)envv('ADMIN_PASSWORD_HASH',''))){ session_regenerate_id(true); $_SESSION['admin_authenticated']=true; header('Location: /admin'); exit; } $error='Credenciais invÃ¡lidas'; } ?><!doctype html><meta charset="utf-8"><title>Admin 360BH</title><h1>Login administrativo</h1><?php if(!empty($error)) echo '<p>'.htmlspecialchars($error).'</p>'; ?><form method="post"><input name="email" type="email" required><input name="password" type="password" required><button>Entrar</button></form><?php exit; }
if ($path === '/admin/logout') { session_destroy(); header('Location: /admin/login'); exit; }
if ($path === '/admin') { admin_required(); $links=db()->query('SELECT id,description,amount_cents,payment_type,status,created_at FROM payment_links ORDER BY id DESC LIMIT 50')->fetchAll(); ?><!doctype html><meta charset="utf-8"><title>Painel 360BH</title><h1>Painel de pagamentos</h1><p><a href="/admin/links/new">Novo link</a> | <a href="/admin/logout">Sair</a></p><table border="1"><tr><th>ID</th><th>DescriÃ§Ã£o</th><th>Valor</th><th>Tipo</th><th>Status</th></tr><?php foreach($links as $l): ?><tr><td><?=$l['id']?></td><td><?=htmlspecialchars($l['description'])?></td><td>R$ <?=money((int)$l['amount_cents'])?></td><td><?=$l['payment_type']?></td><td><?=$l['status']?></td></tr><?php endforeach; ?></table><?php exit; }
if ($path === '/admin/links/new') { admin_required(); if($method==='POST'){ csrf_check(); $raw=public_token(); db()->prepare('INSERT INTO payment_links(token_hash,amount_cents,currency,description,payment_type,expires_at,max_uses,created_by) VALUES(?,?,?,?,?,?,?,?)')->execute([token_hash($raw),(int)$_POST['amount_cents'],'BRL',$_POST['description'],$_POST['payment_type'],$_POST['expires_at']?:null,(int)$_POST['max_uses']?:1,envv('ADMIN_EMAIL')]); $url=rtrim((string)envv('APP_URL'),' /').'/pagar/'.$raw; ?><p>Link criado: <a href="<?=htmlspecialchars($url)?>"><?=htmlspecialchars($url)?></a></p><p><a href="/admin">Voltar</a></p><?php exit; } ?><!doctype html><meta charset="utf-8"><h1>Novo link</h1><form method="post"><input type="hidden" name="_csrf" value="<?=csrf_token()?>"><input name="description" placeholder="DescriÃ§Ã£o" required><input name="amount_cents" type="number" min="1" placeholder="Centavos" required><select name="payment_type"><option value="ONE_TIME">Avulso</option><option value="SUBSCRIPTION">Assinatura mensal</option></select><input name="expires_at" type="datetime-local"><input name="max_uses" type="number" min="1" value="1"><button>Criar</button></form><?php exit; }
http_response_code(404); echo 'Not found';

