<?php
interface Gateway { public function createCustomer(array $customer): string; public function createPayment(array $data): array; public function createSubscription(array $data): array; }
final class AsaasGateway implements Gateway {
    private string $base; private string $key;
    public function __construct() { $this->base = envv('ASAAS_ENVIRONMENT','sandbox') === 'production' ? 'https://api.asaas.com/v3' : 'https://api-sandbox.asaas.com/v3'; $this->key = envv('ASAAS_API_KEY',''); }
    private function call(string $method, string $path, array $body = []): array { if (!$this->key) throw new RuntimeException('ASAAS_API_KEY nao configurada'); $ch=curl_init($this->base.$path); $json=$body?json_encode($body,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES):null; curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_CUSTOMREQUEST=>$method,CURLOPT_HTTPHEADER=>['Content-Type: application/json','User-Agent: 360BH-Checkout/1.0','access_token: '.$this->key],CURLOPT_POSTFIELDS=>$json,CURLOPT_CONNECTTIMEOUT=>15,CURLOPT_TIMEOUT=>60]); $raw=curl_exec($ch); $curlError=curl_error($ch); $code=(int)curl_getinfo($ch,CURLINFO_HTTP_CODE); curl_close($ch); if($raw===false||$curlError!=='') throw new RuntimeException('Falha de comunicacao com o Asaas'); $data=json_decode((string)$raw,true) ?: []; if($code<200||$code>=300){$description=$data['errors'][0]['description']??'Erro no gateway'; error_log('[asaas] HTTP '.$code.' '.$description); throw new RuntimeException($description, $code);} return $data; }
    public function createCustomer(array $c): string { return $this->call('POST','/customers',['name'=>$c['name'],'email'=>$c['email'],'cpfCnpj'=>$c['cpf_cnpj'],'mobilePhone'=>$c['phone'],'postalCode'=>$c['postal_code']??null,'address'=>$c['address']??null,'addressNumber'=>$c['address_number']??null,'complement'=>$c['complement']??null,'province'=>$c['province']??null,'city'=>$c['city']??null,'externalReference'=>$c['external_reference']??null])['id']; }
    public function createPayment(array $d): array { return $this->call('POST','/payments',['customer'=>$d['gateway_customer_id'],'billingType'=>$d['billing_type']??'UNDEFINED','value'=>money($d['amount_cents']),'dueDate'=>$d['due_date']??date('Y-m-d'),'description'=>$d['description']??'Cobrança 360BH','externalReference'=>$d['external_reference']??null]); }
    public function createTransparentPayment(array $d): array { return $this->call('POST','/payments',['customer'=>$d['gateway_customer_id'],'billingType'=>'CREDIT_CARD','value'=>money($d['amount_cents']),'dueDate'=>$d['due_date']??date('Y-m-d'),'description'=>$d['description']??'Cobranca 360BH','externalReference'=>$d['external_reference']??null,'creditCard'=>$d['creditCard'],'creditCardHolderInfo'=>$d['creditCardHolderInfo'],'remoteIp'=>$d['remoteIp']??($_SERVER['REMOTE_ADDR']??'')]); }
    public function pix(string $paymentId): array { return $this->call('GET','/payments/'.rawurlencode($paymentId).'/pixQrCode'); }
    public function boleto(string $paymentId): array { return $this->call('GET','/payments/'.rawurlencode($paymentId).'/identificationField'); }
    public function createSubscription(array $d): array { return $this->call('POST','/subscriptions',['customer'=>$d['gateway_customer_id'],'billingType'=>$d['billing_type']??'UNDEFINED','value'=>money($d['amount_cents']),'nextDueDate'=>$d['due_date']??date('Y-m-d'),'cycle'=>$d['cycle']??'MONTHLY','description'=>$d['description']??'Assinatura 360BH','externalReference'=>$d['external_reference']??null]); }
}
